---
# Setup a PiHole container with some volumes mounted for container persistence.

- name: Ensure pihole etc directory exists
  file:
    path: /data/pihole/etc-pihole
    state: directory

- name: Ensure pihole dnsmasqd directory exists
  file:
    path: /data/pihole/etc-dnsmasqd
    state: directory

- name: Ensure pihole docker container is running
  community.general.docker_container:
    name: pihole
    image: pihole/pihole:latest
    published_ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    restart_policy: unless-stopped
    restart: no
    volumes:
      - /data/pihole/etc-pihole/:/etc/pihole/
      - /data/pihole/etc-dnsmasqd/:/etc/dnsmasq.d/
    dns_servers:
      - '127.0.0.1'
      - '1.1.1.1'
    env:
      TZ: 'Europe/London'
      DNS1: '127.0.0.1'
      DNS2: '1.1.1.1'
      CONDITIONAL_FORWARDING: "{{ pihole_conditional_forwarding }}"
      CONDITIONAL_FORWARDING_IP: "{{ pihole_conditional_forwarding_ip }}"
      CONDITIONAL_FORWARDING_DOMAIN: "{{ pihole_conditional_forwarding_domain }}"
    container_default_behavior: compatibility
